name: dropbox
author: Manuel Mazzuola <manuel.mazzuola@gmail.com>
version: 0.0.1
description: Dropopbox api client
dependencies:
  http: any
  json_object: any
  oauth2:
    path: /home/manuel/src/dart-repo/dart-repo/dart/pkg/oauth2
  unittest: any
